### ISSUE TITLE
Улучшение Product Vision и User Stories

### ISSUE THREAD

**Issue by nvamelichev** [kaledinandrew/TicTacToeOnline#2]
Vision
- [x] Scope (что будет/что не будет в проекте) &mdash; обобщить, а конкретные подробности функциональности перенести в User Stories
- [x] Подумать, чат &mdash; в scope или out of scope для вашего проекта?
- [x] Подумать про остановку/приостановку и возобновление игры, раз упор делается на казуальную игру
- [x] Риски: опыт бэкенд-разработки есть только у 40% команды, а проект масштабный. (Как сгладить риск: делиться знаниями с коллегами по команде, помогать друг другу, выстроить хорошую культуру общения, не бояться давать новичкам более сложные задачи и т.д.)

User Stories
- [x] Истории лучше нумерованным списком сделать, а не маркированным
- [x] S#1: Нужно переформулировать, типа: &laquo;Включиться в игру просто [без регистрации и смс :-D]&raquo;
- [x] S#2: Нужно переформулировать. Про &laquo;Хочу играть со знакомыми игроками&raquo; вместо подробностей про ID. Заодно это закладывает основу, например, для списка недавних игр и игроков и для чатов (если сформулировать требование в виде &laquo;Хочу играть **и общаться** со знакомыми игроками&raquo;).
- [x] S#3, S#4: Нужно переформулировать, и, возможно, объединить в одно требование про **казуальную игру**. Типа: &laquo;Как казуальный игрок, я хочу быстро начинать и завершать игру, чтобы &hellip;&raquo;
- [x] S#5: Нужно переформулировать. Смысл требования &mdash; &laquo;хотим интерактивное приложение, но консольное&raquo;.
- [x] Вписать опциональные требования (можно прям отметить перед историей - [optional])
  - [x] S#6: Таблицы, рейтинги, турниры &mdash; убрать подробную информацию про это из Vision и добавить в User Stories
  - [x] S#7: Продумать истории про кастомизацию. Чем игроки будут отличаться друг от друга? Чем будут хвастаться?

**Comment by kaledinandrew** [comment]
Fixed
